name: Refinance Rate Alert

on:
  schedule:
    # Run daily at 8 AM PST (4 PM UTC)
    - cron: '0 16 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-rates:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file
      run: |
        cat > .env << EOF
        SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD=${{ secrets.SENDER_PASSWORD }}
        RECIPIENT_EMAIL=${{ secrets.RECIPIENT_EMAIL }}
        TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
        EOF
    
    - name: Run rate alert check
      run: python rate_alert.py
    
    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: rate-alert-logs
        path: rate_alert.log 